export const mutationsAccount = {
  SET_TOKEN: 'SET_TOKEN',
  SET_MENUS: 'SET_MENUS',
  SET_AUTHORITIES: 'SET_AUTHORITIES',
  SET_PUBLICUSERINFO: 'SET_PUBLICUSERINFO',
  SET_ACCOUNT_JURISDICTION_AREA_INFO: 'SET_ACCOUNT_JURISDICTION_AREA_INFO',
  SET_CALENDAR_MONTH_REPORT_INFORMATIONS:
    'SET_CALENDAR_MONTH_REPORT_INFORMATIONS',
  SET_CALENDAR_ONEDAY_REPORT_INFORMATIONS:
    'SET_CALENDAR_ONEDAY_REPORT_INFORMATIONS',
  SET_REPORT_REMIND_NEARBY_PERSONS: 'SET_REPORT_REMIND_NEARBY_PERSONS',
  SET_REPORT_REMIND_UNREPORT_PERSONS: 'SET_REPORT_REMIND_UNREPORT_PERSONS'
}
