export const mutationSupervision = {
  GET_REPORT_REMIND_LIST: 'GET_REPORT_REMIND_LIST',
  SET_REPORT_REMIND_RESULT: 'SET_REPORT_REMIND_RESULT',
  GET_REPORT_OUT_LIST: 'GET_REPORT_OUT_LIST',
  SET_REPORT_OUT_DETAIL: 'SET_REPORT_OUT_DETAIL',
  SET_REPORT_OUT_RESULT: 'SET_REPORT_OUT_RESULT'
}
