export const mutationCorrectionStaff = {
  GET_CORRECTIONAL_PAGE: 'GET_CORRECTIONAL_PAGE',

  SET_CORRECTIONAL_AUTH_RESULT: 'SET_CORRECTIONAL_AUTH_RESULT',

  SET_CORRECTIONAL_STAFF_DETAIL: 'SET_CORRECTIONAL_STAFF_DETAIL',

  SET_CORRECTIONAL_STAFF_FILE_LISTS: 'SET_CORRECTIONAL_STAFF_FILE_LISTS',

  SET_CORRECTIONAL_EDIT_RESULT: 'SET_CORRECTIONAL_EDIT_RESULT'
}
