export const mutationsGlobal = {
  SET_COMPONENTS_KEEPALIVE: 'SET_COMPONENTS_KEEPALIVE',
  SET_LOADING: 'SET_LOADING',
  SET_COUNTY: 'SET_COUNTY',
  SET_CITY: 'SET_CITY',
  SET_PROVINCE: 'SET_PROVINCE',
  SET_JURISDICTION: 'SET_JURISDICTION'
}
